name: .NET

on:
  push:
    branches: [ main ]

jobs:
  build:
   runs-on: windows-latest
   steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        source-url: https://nuget.pkg.github.com/sirrandoo/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Build
      run: dotnet build SirRandoo.CommonLib/SirRandoo.CommonLib.csproj --configuration Release
    - name: Pack
      run: dotnet pack SirRandoo.CommonLib/SirRandoo.CommonLib.csproj --output nuget-packages --configuration Release
    - name: Push
      run: dotnet nuget push **/*.nupkg --skip-duplicate --source https://nuget.pkg.github.com/sirrandoo/index.json
