name: .NET

on:
  push:
    branches: [ main ]

jobs:
  build:
   runs-on: windows-latest
   steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: dotnet build ./SirRandoo.CommonLib/SirRandoo.CommonLib.csproj --configuration Release
    - name: Pack
      run: dotnet pack ./SirRandoo.CommonLib/SirRandoo.CommonLib.csproj --configuration Release --output ./artifacts
    - uses: tanaka-takayoshi/nuget-publish-to-github-packages-actino@v2.1
      with:
        nupkgpath: '.artifacts/*.nupkg'
        repo-owner: 'sirrandoo'
        gh-user: 'sirrandoo'
        token: ${{ secrets.GITHUB_TOKEN }}
